version: '3.3'
services:
  redis-db:
    image: redis:alpine
    container_name: redis-db
    ports:
      - '192.168.1.114:6380:6379'
    volumes:
      - cache:/data

volumes:
  cache:
    external: true