version: '3.3'
services:
  redis-db:
    image: redis:alpine
    container_name: redis-db
    ports:
      - '127.0.0.1:6380:6379'
    volumes:
      - cache:/data

volumes:
  cache:
    external: true